# Generated by Django 3.2.9 on 2021-12-12 14:36

from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='form',
        ),
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AddField(
            model_name='form',
            name='confirmed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(default=forms.models.Link.generate_key, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.link')),
                ('confirmation', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='forms.form')),
            ],
            bases=('forms.link',),
        ),
    ]
