# Generated by Django 3.2.8 on 2021-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20211107_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='default',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
