# Generated by Django 3.2.8 on 2021-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_input_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='default',
        ),
        migrations.RemoveField(
            model_name='input',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='key',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default='Form', max_length=256),
        ),
    ]
